#!/bin/bash

set -e

source common

if [ "${ADDRESSES[$REGION_ID]}" = "$HUB_ADDR" ]; then
  run storage_broker "$NEON_DIR/target/release/storage_broker --listen-addr=0.0.0.0:50051"
else
  rm -f logs/storage_broker.pid logs/storage_broker.log
fi

until (mc alias set minio http://$HUB_ADDR:9000 minioadmin minioadmin) do
    echo 'Waiting to start minio...' && sleep 1
done
data=./data
mkdir -p $DATA
rm -rf $DATA/.neon
mc cp -r minio/neon/.neon $DATA/

run pageserver "$NEON_DIR/target/release/pageserver -D $DATA/.neon/ \
  -c broker_endpoint='http://$HUB_ADDR:50051'                       \
  -c listen_pg_addr='0.0.0.0:6400'                                  \
  -c listen_http_addr='0.0.0.0:9898'"

run safekeeper "$NEON_DIR/target/release/safekeeper \
  --id=1                                            \
  --datadir=$DATA                                   \
  --advertise-pg=${ADDRESSES[$REGION_ID]}:5454      \
  --listen-pg=0.0.0.0:5454                          \
  --listen-http=0.0.0.0:7676                        \
  --broker-endpoint=http://$HUB_ADDR:50051"
