#!/bin/bash

source common

set -eux

# Generate a random tenant or timeline ID
#
# Takes a variable name as argument. The result is stored in that variable.
generate_id() {
    local -n resvar=$1
    printf -v resvar '%08x%08x%08x%08x' $RANDOM $RANDOM $RANDOM $RANDOM
}

PG_VERSION=${PG_VERSION:-14}

SPEC_FILE_ORG=spec-template.json
SPEC_FILE=spec.json

echo "Waiting pageserver become ready."
while ! nc -z localhost 6400; do
     sleep 1;
done
echo "Page server is ready."

echo "Create a tenant and timeline"
generate_id tenant_id
PARAMS=(
     -sb 
     -X POST
     -H "Content-Type: application/json"
     -d "{\"new_tenant_id\": \"${tenant_id}\"}"
     http://localhost:9898/v1/tenant/
)
result=$(curl "${PARAMS[@]}")
echo $result | jq .

generate_id timeline_id
PARAMS=(
     -sb 
     -X POST
     -H "Content-Type: application/json"
     -d "{\"new_timeline_id\": \"${timeline_id}\", \"pg_version\": ${PG_VERSION}}"
     "http://localhost:9898/v1/tenant/${tenant_id}/timeline/"
)
result=$(curl "${PARAMS[@]}")
echo $result | jq .

echo "Overwrite tenant id and timeline id in spec file"
sed "s/TENANT_ID/${tenant_id}/" ${SPEC_FILE_ORG} > ${SPEC_FILE}
sed -i "s/TIMELINE_ID/${timeline_id}/" ${SPEC_FILE}

cat ${SPEC_FILE}

run compute "$NEON_DIR/target/release/compute_ctl --pgdata $DATA/compute \
     -C "postgresql://cloud_admin@localhost:55433/postgres"  \
     -b $NEON_DIR/pg_install/v14/bin/postgres                \
     -S ${SPEC_FILE}"
