#!/bin/bash

# The directory of the xactserver repo
XACTSERVER_DIR=$HOME/src/sunstorm/xactserver
# The directory of the neon repo
NEON_DIR=$HOME/src/sunstorm/neon

run() {
  name=$1
  cmd=$2
  mkdir -p logs
  echo "Starting $name"
  set -x
  nohup $cmd > logs/$name.log 2>&1 &
  set +x
  echo $! > logs/$name.pid
  echo "Process $name pid: $(cat logs/$name.pid)"
}
