#!/bin/bash

DATA=/home/ubuntu/data

set -eu

usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "      --master-addrs  Comma-separated list of master addresses [required]"
    echo "      --tserver-addrs Comma-separated list of tserver addresses [required]"
    echo "      --master        Run the master"
    echo "      --tserver       Run the tserver"
    echo "      --region-id     The region id"
    echo "      --tserver-id    The tserver id"
    echo "      --stop          Only stop the components"
    echo "  -n, --new           Start with new data"
    exit 1
}

run_master=0
run_tserver=0
tserver_id=0
stop_only=0
new_data=0
region_id=0
flag_set=0
master_addrs_str=""
tserver_addrs_str=""

while (( "$#" )); do
    case "$1" in
        --master-addrs)
            master_addrs_str=$2
            shift 2
        ;;
        --tserver-addrs)
            tserver_addrs_str=$2
            shift 2
        ;;
        -m|--master)
            run_master=1
            flag_set=1
            shift 1
        ;;
        -t|--tserver)
            run_tserver=1
            flag_set=1
            shift 1
        ;;
        --tserver-id)
            tserver_id=$2
            shift 2
        ;;
        --stop)
            stop_only=1
            shift 1
        ;;
        --region-id)
            region_id=$2
            shift 2
        ;;
        -n|--new)
            new_data=1
            shift 1
        ;;
        -h|--help)
            usage
        ;;
        *) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            usage
        ;;
    esac
done

if [ "$stop_only" -eq 0 ] && [ -z "$master_addrs_str" ]; then
    echo "Error: Missing --master-addrs" >&2
    usage
fi

if [ "$stop_only" -eq 0 ] && [ -z "$master_addrs_str" ]; then
    echo "Error: Missing --tserver-addrs" >&2
    usage
fi

# Split the comma-separated master addresses into an array
IFS=',' read -r -a master_addrs <<< "$master_addrs_str"

# Split the comma-separated tserver addresses into an array
IFS=',' read -r -a tserver_addrs <<< "$tserver_addrs_str"

# If no components are specified, start all of them
if [ $flag_set -eq 0 ]; then
    run_master=1
    run_tserver=1
fi

# Remove data directory if starting anew
if [ $stop_only -eq 0 ] && ([ ! -d $DATA ] || [ $new_data -eq 1 ]); then
    echo "Removing $DATA"
    rm -rf $DATA
    mkdir -p $DATA
fi

if [ $run_master -eq 1 ]; then
    echo "Stopping any previous master instance"
    pkill -e yb-master || true

    if [ $stop_only -eq 0 ]; then
        echo "Starting master"
        /home/ubuntu/yugabyte-2.20.0.1/bin/yb-master                 \
        --master_addresses=${master_addrs_str}                       \
        --fs_data_dirs=$DATA                                         \
        --rpc_bind_addresses=0.0.0.0                                 \
        --server_broadcast_addresses=${master_addrs[$region_id - 1]} \
        --placement_cloud=aws                                        \
        --placement_region=region-$region_id                         \
        --placement_zone=region-$region_id                           \
        --leader_failure_max_missed_heartbeat_periods=10             \
        > /home/ubuntu/yb-master.out 2>&1 &
    fi
fi

if [ $run_tserver -eq 1 ]; then
    echo "Stopping any previous tserver instance"
    pkill -e yb-tserver || true

    if [ $stop_only -eq 0 ]; then
        echo "Starting tserver"
        /home/ubuntu/yugabyte-2.20.0.1/bin/yb-tserver                 \
        --tserver_master_addrs=${master_addrs_str}                    \
        --fs_data_dirs=$DATA                                          \
        --rpc_bind_addresses=0.0.0.0                                  \
        --server_broadcast_addresses=${tserver_addrs[$tserver_id]}    \
        --cql_proxy_bind_address=0.0.0.0:9042                         \
        --pgsql_proxy_bind_address=0.0.0.0:5433                       \
        --webserver_interface=0.0.0.0                                 \
        --placement_cloud=aws                                         \
        --placement_region=region-$region_id                          \
        --placement_zone=region-$region_id                            \
        --leader_failure_max_missed_heartbeat_periods=10              \
        > /home/ubuntu/yb-tserver.out 2>&1 &
    fi
fi
